[package]
name = "mullvad-daemon"
version = "2019.4.0"
authors = [
    "Mullvad VPN <admin@mullvad.net>",
    "Andrej Mihajlov <and@mullvad.net>",
    "Emīls Piņķis <emils@mullvad.net>",
    "Erik Larkö <erik@mullvad.net>",
    "Janito Vaqueiro Ferreira Filho <janito@mullvad.net>",
    "Linus Färnstrand <linus@mullvad.net>",
]
description = "Mullvad VPN daemon. Runs and controls the VPN tunnels"
license = "GPL-3.0"
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.25"
err-derive = "0.1.5"
fern = { version = "0.5", features = ["colored"] }
futures = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
log-panics = "2.0.0"
jsonrpc-core = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
jsonrpc-macros = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
jsonrpc-pubsub = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
jsonrpc-ipc-server = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
ipnetwork = "0.14"
uuid = { version = "0.7", features = ["v4"] }
lazy_static = "1.0"
rand = "0.6"
tokio-core = "0.1"
tokio-timer = "0.1"
regex = "1.0"

mullvad-ipc-client = { path = "../mullvad-ipc-client" }
mullvad-paths = { path = "../mullvad-paths" }
mullvad-types = { path = "../mullvad-types" }
mullvad-rpc = { path = "../mullvad-rpc" }
talpid-core = { path = "../talpid-core" }
talpid-ipc = { path = "../talpid-ipc" }
talpid-types = { path = "../talpid-types" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
simple-signal = "1.1"

[target.'cfg(windows)'.dependencies]
ctrlc = "3.0"
windows-service = { git = "https://github.com/mullvad/windows-service-rs.git", rev = "aab5b26beae364253802b6e5554c9ecdc6285454" }
winapi = "0.3"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"

[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Amagicom AB"
LegalCopyright = "(c) 2018 Amagicom AB"
InternalName = "mullvad-daemon"
OriginalFilename = "mullvad-daemon.exe"
