[package]
name = "conductor-cli"
version = "0.1.0"
authors = ["bowen.yan <bowen.yan@siteview.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
clap = "2.32"
conductor-core = { path = "../conductor-core" }
rand = "0.7"
